language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - php vendor/bin/phpunit --testsuite playgroundgameC
  - php vendor/bin/phpunit --testsuite playgroundgameE
  - php vendor/bin/phpunit --testsuite playgroundgameF
  - php vendor/bin/phpunit --testsuite playgroundgameM
  - php vendor/bin/phpunit --testsuite playgroundgameS
